### Tensors

Tensors are a speciallized data structure (similar to an array or a matriz)
In PyTorch, the tensors are used to encode the inputs and outputs of a model (as well as the model's parameters).

In a easy way for developers, tensors are similar to numpy arrays `ndarray`, but they can also be used on a GPU or other accelerator hardware.


Even, tensors and ndarrays can often share the same underlying memory, avoiding the need to copy data (see `torch.Tensor.numpy` and `torch.from_numpy`).

In [1]:
import torch
import numpy as np

#### Initializing a tensor

Tensors can be initialized in a several ways:
* Directly from data

In [7]:
data = [[1, 4], [2, 5]]
x_data = torch.tensor(data=data)
x_data

tensor([[1, 4],
        [2, 5]])

* Form a numpy array

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 4],
        [2, 5]])

* From another tensor
The new tensor retains the properties (shape, datatype) of the given tensor, unless explicitly overridden.

In [12]:
x_ones = torch.ones_like(x_data)
x_ones
print(f"Ones Tensor: \n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n{x_rand}")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])
Random Tensor: 
tensor([[0.4415, 0.6139],
        [0.9234, 0.7112]])


#### With random or constant values

In [23]:
shape = (3, 3)
torch.ones(shape, dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [25]:
torch.zeros(size=shape, dtype=torch.float)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

#### Attibutes of a tensor

In [29]:
tensor = torch.rand(shape)
print(f"Tensor: \n{tensor}")
print(f"Tensor Shape: {tensor.shape}")
print(f"Tensor Datatype: {tensor.dtype}")
print(f"Tensor Device: {tensor.device}")

Tensor: 
tensor([[0.1196, 0.8462, 0.2066],
        [0.4413, 0.4624, 0.7521],
        [0.4049, 0.8000, 0.6639]])
Tensor Shape: torch.Size([3, 3])
Tensor Datatype: torch.float32
Tensor Device: cpu


#### Operations on Tensors
There are over 100 tensor operations, including arithmetic, linear algebra, matrix maniputation (slicing, indexing, transposing...), sampling and [more](https://pytorch.org/docs/stable/torch.html)

It's recommended to use gpu for the operations, for a better performance than the cpu.

In [31]:
print(torch.cuda.is_available()) # if True, tensor = tensor.to('cuda)


False


##### Indexing, Slicing, Joining, Mutating Ops (NumPy like)

In [36]:
tensor = torch.rand(4, 4)
print(f"Tensor: \n{tensor}")
print(f"First row: \n{tensor[0]}")
print(f"First column \n{tensor[:, 0]}")
print(f"Last row: \n{tensor[-1]}")
print(f"Last Column: \n{tensor[:, -1]}")



Tensor: 
tensor([[0.8397, 0.9427, 0.0916, 0.1292],
        [0.0878, 0.7053, 0.3313, 0.7996],
        [0.8941, 0.1002, 0.6931, 0.1012],
        [0.2395, 0.0227, 0.7815, 0.5145]])
First row: 
tensor([0.8397, 0.9427, 0.0916, 0.1292])
First column 
tensor([0.8397, 0.0878, 0.8941, 0.2395])
Last row: 
tensor([0.2395, 0.0227, 0.7815, 0.5145])
Last Column: 
tensor([0.1292, 0.7996, 0.1012, 0.5145])


In [41]:
# tensor [start:end, start:end]
print(tensor[1:3, 1:3])

tensor([[0.7053, 0.3313],
        [0.1002, 0.6931]])


##### Join tensors
You can use `torch.cat` to concatenate a sequence of tensors, along a given dimension.
Important: the dim is the axis to concatenate (0 is the row, 1 is the column)


In [56]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)
t1 = torch.cat([tensor, tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


__Arithmetic operations__

In [64]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)

torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [69]:
# This computes the element-wise product. z1, z2, z3 will have the same value.
z1 = tensor * tensor.T
z2 = tensor.mul(tensor.T)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out=z3)
print(z3)

tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


__Single-element tensor__
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`

In [70]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


__In-place operations__: operations that store the result into the operand are called _in-plece_. They are denoted by `_` suffix. For example: `x.copy_(y)` or `x.t_()` will change `x`.

In [5]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
tensor.add_(8)

tensor([[9., 8., 9., 9.],
        [9., 8., 9., 9.],
        [9., 8., 9., 9.],
        [9., 8., 9., 9.]])

#### Bridge with NumPy
Tensor on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.x

##### Tensor to NumPy array

In [12]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(f"Tensor: \n{tensor}")
n = tensor.numpy()
print(f"Numpy: \n{n}")
torch.from_numpy(n)

Tensor: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Numpy: 
[[1. 0. 1. 1.]
 [1. 0. 1. 1.]
 [1. 0. 1. 1.]
 [1. 0. 1. 1.]]


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Any change on the tensor reflects on the NumPy array.

In [13]:
tensor.add_(1)
print(f"Tensor: \n{tensor}")
print(f"Numpy: \n{n}")

Tensor: 
tensor([[2., 1., 2., 2.],
        [2., 1., 2., 2.],
        [2., 1., 2., 2.],
        [2., 1., 2., 2.]])
Numpy: 
[[2. 1. 2. 2.]
 [2. 1. 2. 2.]
 [2. 1. 2. 2.]
 [2. 1. 2. 2.]]


##### NumPy array to Tensor

In [16]:
n = np.ones((4, 4))
t = torch.from_numpy(n)
print(f"Numpy: \n{n}")
print(f"Tensor: \n{t}")
n = np.add(n, 1, out=n)
print(f"Numpy: \n{n}")
print(f"Tensor: \n{t}")

Numpy: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Tensor: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
Numpy: 
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
Tensor: 
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)
